.TH NL-TX 1 "May 2018" "Kontron-TSN" "User Commands"
.SH NAME
nl-tx \- send frames for latency measurements
.SH SYNOPSIS
\fBnl-tx\fR [OPTION] ... <interface>
.SH DESCRIPTION
.B nl-tx
Generate test packets that contains additional information for
latency measurements.
.SH OPTIONS
.SH EXIT STATUS
.SH EXAMPLE
.SH SEE ALSO

